server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: bookuser
    password: fizzingwhizbee
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: none