DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(
    BOOK_ID SERIAL PRIMARY KEY,
    ISBN VARCHAR(250),
    BOOK_NAME VARCHAR(250),
    DESCRIPTION VARCHAR(250),
    AUTHOR VARCHAR(250),
    PUBLICATION_YEAR INTEGER,
    SMALL_IMAGE_URL VARCHAR(250),
    LARGE_IMAGE_URL VARCHAR(250),
    PRICE NUMERIC(10,2) ,
    NUMBER_OF_AVAILABLE_BOOKS integer,
    RATING NUMERIC(10,2)
)



