DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
ISBN VARCHAR(250) PRIMARY KEY, -- ISBN
BOOK_NAME  VARCHAR(250),
DESCRIPTION VARCHAR(250),
AUTHOR VARCHAR(250),
PUBLICATION_YEAR INTEGER,
SMALL_IMAGE_URL VARCHAR(250),
LARGE_IMAGE_URL VARCHAR(250),
PRICE NUMERIC(10,2) ,
NUMBER_OF_AVAILABLE_BOOKS integer,
RATING NUMERIC(10,2)
);


INSERT INTO book VALUES (
'012346', 'React book', 'React Book description','Bala', 2022, 'imageurlsmall/img.img','largeImageurllarge.img', 128.55, 5, 4.8);
INSERT INTO book VALUES (
'012345', 'Java book', 'Book description','Amar', 2023, 'imageurl/img.img','largeImageurl.img', 100.55, 1, 4.5);

