DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    USER_ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    USER_NAME VARCHAR(250),
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ,
    DELETED_AT TIMESTAMPTZ
)