CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS(
    ORDER_ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    ADDRESS VARCHAR(250),
    USER_ID UUID REFERENCES USERS(USER_ID),
    PAYMENT_MODE VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(10,2),
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ,
    DELETED_AT TIMESTAMPTZ
)
