DROP TABLE IF EXISTS ORDER;
CREATE TABLE ORDERS(
    ORDER_ID INTEGER PRIMARY KEY,
    ADDRESS VARCHAR(250),
    CUSTOMER_ID VARCHAR(250) FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    PAYMENT_MODE VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(10,2),
    CREATED_ON DATE
)
