DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
    ORDER_ID SERIAL PRIMARY KEY,
    ADDRESS VARCHAR(250),
    USER_ID INTEGER REFERENCES USERS(USER_ID),
    PAYMENT_MODE VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(10,2),
    CREATED_ON DATE
)
