DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS(
    ORDER_ID INTEGER PRIMARY KEY,
    ADDRESS VARCHAR(250),
    CUSTOMER_ID INTEGER REFERENCES CUSTOMER(CUSTOMER_ID),
    PAYMENT_MODE VARCHAR(50),
    TOTAL_AMOUNT NUMERIC(10,2),
    CREATED_ON DATE
);
