CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS CART;

CREATE TABLE CART (
    CART_ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    USER_ID UUID REFERENCES USERS(USER_ID),
    AMOUNT NUMERIC(10,2),
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ,
    DELETED_AT TIMESTAMPTZ
);
