CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE IF EXISTS CART_ITEM;

CREATE TABLE CART_ITEM (
    CART_ITEM_ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    CART_ID UUID REFERENCES CART(CART_ID),
    BOOK_ID INTEGER REFERENCES BOOK(BOOK_ID),
    QUANTITY INTEGER,
    TOTAL_PRICE NUMERIC(10, 2),
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ,
    DELETED_AT TIMESTAMPTZ
);
